# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Home"
#  url = "/"
#  weight = 10

[[main]]
  name = "天之五绝"
  url = "post"
  weight = 20

[[main]]
  name = "影界使者"
  url = "post2"
  weight = 30

[[main]]
  name = "人物"
  url = "people"
  weight = 50

#[[main]]
 # name = "事件"
  #url = "event"
  #weight = 60

#[[main]]
 # name = "Publications"
 # url = "publication"
  #weight = 70

[[main]]
  name = "联系"
  url = "contact"
  weight = 80
